### ISSUE TITLE
TinyMCE doesn't load at all in Safari or Firefox on macOS Sierra

### ISSUE THREAD

**Issue by arlomedia** [tinymce/tinymce#8420]
**What is the current behavior? Describe the bug**

I just upgraded my website from TinyMCE 4.9 to the latest TinyMCE 6 version. Now I see that on older Mac computers with Sierra, TinyMCE doesn't load at all in the latest supported version of Safari (12.1.2) or Firefox (33.1). There's just a blank space where TinyMCE should appear on the page. The same problem happens with the demo installation at tiny.cloud. The browser console shows "TypeError: undefined is not a function (near '...Promise.allSettled...')"

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

From Safari or Firefox on macOS Sierra, go to tiny.cloud and look at the space where TinyMCE should be.

**What is the expected behavior?**

TinyMCE appears and can be used, perhaps with some functional limitations. Hopefully there are some fixes that could be made to restore this browser support.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE 6.3.1, macOS 10.12.6, Safari 12.1.2, Firefox 33.1. It worked in TinyMCE 4.9.5.

Also, I found the system requirements page for TinyMCE and it said Safari and Firefox were supported on macOS, but with no details about browser or OS versions.

**Comment by TheSpyder** [comment]
TinyMCE 6 explicitly dropped support for old browsers. This is documented on our website, apologies if it isn't clear:
https://www.tiny.cloud/docs/tinymce/6/support/#supported-web-browsers

> TinyMCE supports the most recent version of all browsers listed above. TinyMCE also supports the latest Extended Support Release (ESR) from each vendor (e.g. Firefox). TinyMCE provides support for the prior major version for 60 days after the release has been superseded by a new major version (e.g. Chrome 98 vs. Chrome 97).

Safari 12 fell out of support by Apple in late 2019.
Firefox 33 was not an ESR release, the ESR at the time (31) fell out of support by Mozilla in mid 2015.

Note that while Safari no longer supports macOS 10.12, Firefox does:
https://www.mozilla.org/en-US/firefox/109.0.1/system-requirements/

TinyMCE 5 might still work for you, or alternatively upgrade Firefox to the latest release; that should work with TinyMCE 6 (although you still won't be able to use Safari).
