### ISSUE TITLE
[BUG] Uncaught (in promise): TypeError: fontFamily.replace is not a function on destroy action

### ISSUE THREAD

**Issue by morozow** [tinymce/tinymce#3765]
Hello, everybody.

**Framework**: Angular
**Use case**: textarea with tinymce Angular dicrective.
**Tynymce package**: "tinymce": "^4.6.3",
**Issue**: We have lifecycle method in Angular called onDestroy. This method invokes before Angular directive will be destroyed.
In this method I call `editor.destroy()` method and have an Uncaught exception. Stack trace in below:

> ERROR Error: Uncaught (in promise): TypeError: fontFamily.replace is not a function
TypeError: fontFamily.replace is not a function
    at normalizeFontFamily (http://localhost:8080/app/app.bundle-92563952a2c38322b634.js:125611:25)
    at Object.getFontFamily (http://localhost:8080/app/app.bundle-92563952a2c38322b634.js:81726:16)
    at Editor.<anonymous> (http://localhost:8080/app/app.bundle-92563952a2c38322b634.js:125754:35)
    at Dispatcher.fire (http://localhost:8080/app/app.bundle-92563952a2c38322b634.js:104998:31)
    at Editor.fire (http://localhost:8080/app/app.bundle-92563952a2c38322b634.js:105238:41)
    at Object.nodeChanged (http://localhost:8080/app/app.bundle-92563952a2c38322b634.js:115690:18)
    at Editor.nodeChanged (http://localhost:8080/app/app.bundle-92563952a2c38322b634.js:119441:36)
    at Editor.<anonymous> (http://localhost:8080/app/app.bundle-92563952a2c38322b634.js:99843:18)
    at Dispatcher.fire (http://localhost:8080/app/app.bundle-92563952a2c38322b634.js:104998:31)
    at Editor.fire (http://localhost:8080/app/app.bundle-92563952a2c38322b634.js:105238:41)
    at Object.add (http://localhost:8080/app/app.bundle-92563952a2c38322b634.js:99931:18)
    at Editor.addNonTypingUndoLevel (http://localhost:8080/app/app.bundle-92563952a2c38322b634.js:99731:14)
    at Dispatcher.fire (http://localhost:8080/app/app.bundle-92563952a2c38322b634.js:104998:31)
    at Editor.fire (http://localhost:8080/app/app.bundle-92563952a2c38322b634.js:105238:41)
    at Editor.save (http://localhost:8080/app/app.bundle-92563952a2c38322b634.js:119855:16)
    at Editor.remove (http://localhost:8080/app/app.bundle-92563952a2c38322b634.js:120302:16)
    at Editor.destroy (http://localhost:8080/app/app.bundle-92563952a2c38322b634.js:120351:16)

This issue is actual only when my Tinymce textarea have been prepopulated with some text/html/etc. when directive created (i.e. tinymce textarea have editor.setContent() in the `init_instance_callback` init config)

**Expected result**: No uncaught exception.

Do anyone have the same problem?
It can be Angular integration issue as well.

**Comment by Kuresov** [comment]
I've been seeing this as well with a `beforeDestroy` callback in Vue. Maybe a race condition? Seems to happen intermittently (albeit frequently) in my case.

**Comment by morozow** [comment]
@Kuresov Yes, it is similar for me. But I mentioned that there is no error if tinymce didn't have any initial value, only with some initialized value.
So, this behavior can be named unstable.

**Comment by fabgallo** [comment]
We are experiencing the same issue. Our project is in Angular 1.5 and we started seeing the error after upgrading from 4.5.1 to latest (4.6.4).

The error
>TypeError: fontFamily.replace is not a function
    at normalizeFontFamily (tinymce.js:51781)
    at Object.getFontFamily (tinymce.js:7383)
    at Editor.<anonymous> (tinymce.js:51924)
    at Dispatcher.fire (tinymce.js:30845)
    at Editor.fire (tinymce.js:31085)
    at Object.nodeChanged (tinymce.js:41635)
    at Editor.nodeChanged (tinymce.js:45606)
    at Editor.<anonymous> (tinymce.js:25580)
    at Dispatcher.fire (tinymce.js:30845)
    at Editor.fire (tinymce.js:31085)

happens not only when we do `editor.setContent()` in the `init_instance_callback`, but also if we do just `editor.undoManager.clear()`.

The error seems to happen only with editable areas that are **NOT** in inline mode.

As mentioned by @morozow , when the error happens, `fontFamily` is not a string but an object
![image](https://user-images.githubusercontent.com/2903427/27865822-11750fb8-6162-11e7-8860-73f0a76fa4b3.png)

**Comment by oleksiipavlenko** [comment]
Same problem when textarea empty and call editor.remove()

**Comment by dzena** [comment]
I have exactly the same problem with Angular2 project. So far, didn't find any workaround.

**Comment by oleksiipavlenko** [comment]
In my case, the problem appeared with the using "execCommand" for changing default editor values. 
It was fixed by adding [content_css](https://www.tinymce.com/docs-3x//reference/configuration/Configuration3x@content_css/#exampleofusageofthecontent_cssoption) option.
Works fine for both versions.

**Comment by SimonBrodtmann** [comment]
Any comment from a developer?

**Comment by Iworb** [comment]
Got the same error using `destroy` method` to re-init tinyMCE instance.

**Comment by decodingpanda** [comment]
I got the same issue, after I call tinymce.remove()

**Comment by spocke** [comment]
Is this still an issue with 4.7.2 if so please provide us with a fiddle.tinymce.com url where it can be reproduced.

**Comment by twenty** [comment]
We upgraded from TinyMCE 4.3.4 -> TinyMCE 4.7.4 last night (funnily enough to resolve an issue with removing an instance in Edge) and have noticed this exact issue, although we are not using Angular.

Only occurs when we call remove() on a TinyMCE instance that has the "fontSelect" option in the toolbar and we are able to replicate it every time.

Perhaps this is an integration issue as we cannot replicate in Fiddle, however the editor code hasn't changed in months and was working flawlessly before the update.

> theme.js:14224 Uncaught TypeError: fontFamily.replace is not a function
    at normalizeFontFamily (theme.js:14224)
    at Object.getFontFamily (theme.js:531)
    at Editor.<anonymous> (theme.js:14296)
    at Dispatcher.fire (tinymce.js:23139)
    at Editor.fire (tinymce.js:23379)
    at Object.nodeChanged (tinymce.js:26865)
    at Editor.nodeChanged (tinymce.js:40544)
    at Editor.<anonymous> (tinymce.js:28970)
    at Dispatcher.fire (tinymce.js:23139)
    at Editor.fire (tinymce.js:23379)

**Comment by fabgallo** [comment]
I have been successful in _avoiding_ this error by setting `editor.initialized = false` just before calling `editor.remove()`. Our use case allows for this as, at the time of removal, we already saved the tinymce content in our model and we don't need to do anything else with it

**Comment by spocke** [comment]
Closing this one since the fontFamily issue has been fixed and released and we have no way of reproducing any other issue. If a fiddle with a standalone case can be provided we might re-open this ticket.

**Comment by fabgallo** [comment]
@spocke do you mind sharing which version of tinymce fixed the fontFamily issue? I couldn't find it in the changelog. I am on 4.7.4 and still experience the bug (unless I `editor.initialized = false` just before calling `editor.remove()`)

**Comment by spocke** [comment]
I think it was back in 4.6.2 we need to be able to reproduce this in order to fix it. The fix we added is that it checks if the element is still in the dom when it computes the font size/font family. You shouldn't need to set editor.initialized ever.

Stuff like this normally happens when the editor is clobbered white it's being rendered. It tries to access the dom of the iframe and the element is no longer there. The editor initialization is async so one should really wait for it to be loaded properly before destroying it. We have official integrations for react and angular that works better with this life cycle management.

**Comment by gpashis** [comment]
I am getting an similar issue "Uncaught TypeError: rawToolbar.replace is not a function" from theme.js. 

> Uncaught TypeError: rawToolbar.replace is not a function
>     at extract$1 (theme.js:10428)
>     at identify (theme.js:10438)
>     at Object.detect$4 [as detect] (theme.js:10536)
>     at Editor.<anonymous> (theme.js:14296)
>     at EventDispatcher.fire (tinymce.js:25608)
>     at Editor.fire (tinymce.js:25714)
>     at initEditor (tinymce.js:23786)
>     at tinymce.js:23900
>     at tinymce.js:4479
>     at tinymce.js:4136

**Comment by paulwangtao** [comment]
5094:1 Uncaught SyntaxError: Illegal return statement
at normalizeFontFamily (theme.js:14121:7)
at Object.getFontFamily (theme.js:931:16)
at Editor. (theme.js:14193:37)
at Dispatcher.fire (tinymce.js:31557:31)
at Editor.fire (tinymce.js:31797:41)
at Object.nodeChanged (tinymce.js:35459:18)
at Editor.nodeChanged (tinymce.js:40240:36)
at Editor. (tinymce.js:37058:18)
at Dispatcher.fire (tinymce.js:31557:31)
at Editor.fire (tinymce.js:31797:41)

because fontFamily is : ( not font string ) 
init [body#tinymce.mce-content-body, context: body#tinymce.mce-content-body]
return typeof fontFamily =='string'?fontFamily.replace(/['"]/g, '').replace(/,\s+/g, ','):'';

modify :
 var normalizeFontFamily = function (fontFamily) {
      // 'Font name', Font -> Font name,Font
      return typeof fontFamily =='string'?fontFamily.replace(/[\'\"]/g, '').replace(/,\s+/g, ','):'';
    }
