### ISSUE TITLE
Hit error "n.__shady_getRootNode is not a function" when press enter (new line) in tinyMCE editor 

### ISSUE THREAD

**Issue by seepengl** [tinymce/tinymce#7528]
hit error "n.__shady_getRootNode is not a function" when press enter in tinyMCE editor after upgraded from version 5.0.15 to 5.8.2. This only happen in browser chrome.

Try to debug further and find out that this line of code in tinyMCE, e.dom.getRootNode() actually is calling the shady_getRootNode in Chrome browser but in FireFox browser it is not calling the shady_getRootNode and it's calling the htmlSpan getRootNode(). So it's working fine in Firefox browser.

![Screenshot 2022-01-19 at 2 46 27 PM](https://user-images.githubusercontent.com/38730660/150080010-2ef9b527-d679-4f52-9838-0d1b5c9a0523.png)

Note: shady_getRootNode is webcomponents polyfills code
![Screenshot 2022-01-19 at 3 32 28 PM](https://user-images.githubusercontent.com/38730660/150084738-3335072d-c0cb-4206-889e-68badc7e7de2.png)

Note: Suspect this issue happen due to the tinyMCE iframe with partial polyfills in chrome browser

Error stack trace:
Uncaught TypeError: n.__shady_getRootNode is not a function
    at HTMLSpanElement.getRootNode 
    at an (tinymce.min.js:formatted:964:33)
    at yn (tinymce.min.js:formatted:1022:13)
    at xn (tinymce.min.js:formatted:1043:58)
    at tinymce.min.js:formatted:7823:20
    at _d (tinymce.min.js:formatted:7824:10)
    at Ad (tinymce.min.js:formatted:7863:9)
    at Dd (tinymce.min.js:formatted:7883:17)
    at tinymce.min.js:formatted:7868:20
    at Bd (tinymce.min.js:formatted:7895:9)

Anyone has any idea how to solve this issue? Thanks.

**Comment by blackjackyau** [comment]
The issue is happened when we have TinyMCE (iframe, not inline mode) running under a webcomponent pollyfill-ed application (https://github.com/webcomponents/polyfills).


Investigation outcome
- As the document object from iframe will not be made pollyfill automatically, all element creation should be made contextualised, E.g. create element in iframe should be using iframe document instead of the top document (pollyfill). Failed to do so will result in broken pollyfill chain as displayed above
- the logic in [here](https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/core/main/ts/dom/ScrollIntoView.ts#L97-L104) failed to do so as it does not forward the iframe document `const doc = SugarElement.fromDom(editor.getDoc());` to the `createMarker(SugarElement.fromDom(rng.startContainer), rng.startOffset);` method to create marker element, and result with a mixture of pollyfill elements
- Did a quick patch by forwarding the iframe document to the `createMarker` and then the `SugarElement.fromHtml`. The error from pollyfill is no longer be seen
```
const applyWithMarker = (editor: Editor, f: ScrollFunc, rng: Range, alignToTop?: boolean) => {
  const body = SugarElement.fromDom(editor.getBody());
  const doc = SugarElement.fromDom(editor.getDoc());

  Css.reflow(body);
  const marker = createMarker(SugarElement.fromDom(rng.startContainer), rng.startOffset, doc);
  withScrollEvents(editor, doc, f, marker, alignToTop);
  marker.cleanup();
};

const createMarker = (element: SugarElement, offset: number, document): MarkerInfo => {
  const startPoint = descend(element, offset);
  const span = SugarElement.fromHtml<HTMLSpanElement>('<span data-mce-bogus="all" style="display: inline-block;">' + Zwsp.ZWSP + '</span>', document);
  Insert.before(startPoint.element, span);

  return markerInfo(span, () => Remove.remove(span));
};
```
