### ISSUE TITLE
4.6.7 regression - windowManager.getParams(...).oninsert is not a function

### ISSUE THREAD

**Issue by vanillajonathan** [tinymce/tinymce#3964]
I was unable to reproduce this with TinyMCE Fiddle because I got another error.
But the code should show what I was trying to do:
http://fiddle.tinymce.com/1bgaab

I use the `file_picker_callback` with a call to `tinymce.activeEditor.windowManager.open` with an params object containing `oninsert` and then call the callback to insert the image.

https://www.tinymce.com/docs/api/tinymce/tinymce.windowmanager/#open

    TypeError: top.tinymce.activeEditor.windowManager.getParams(...).oninsert is not a function

This worked fine in 4.6.6 (and earlier) but no longer works in 4.6.7.

**Comment by XardoniK** [comment]
They fixed this. Is working on 4.7.0.

**Comment by vanillajonathan** [comment]
Yes this appears to be fixed in 4.7.0.

Perhaps there should be a 4.6.8 point release for those who still use the 4.6 branch.

**Comment by Afraithe** [comment]
Maybe, but we would rather like ppl to upgrade to 4.7.

**Comment by vanillajonathan** [comment]
@Afraithe Yes but people running on the 4.6 branch expect (according to [Semantic Versioning](http://semver.org/)) to have it stable and only get bug fixes, not regressions. The 4.6.7 didn't just include bugfixes but also refactoring which should have been left for the 4.7 branch which ended up introducing a regression.

This is not the first time for me that a TinyMCE point release have introduced regressions which ended up affecting websites in production. Last time was also due to refactoring in point releases.

People should upgrade to 4.7 on the basis that it is better, not forced due to the 4.6 being broken due to regressions.

**Comment by spocke** [comment]
The restructuring between 4.6.6 and 4.6.7 was pretty minor there for we pushed that in a patch release. Fixing bugs might also produce regressions so that is not something you can avoid.

We discussed this before releasing 4.7.0 if we need to do a 4.6.8 with only this fix for the getTopMostWindow since that is the only issue we have at the moment. But doing releases on a older branch is something we want to try to limit as much as possible sometimes this is required and we might reconsider if we see more users having the same issue.

So upgrade to 4.7.0 or use editor.windowManger.getWindows() and the params object on that to get params out.

**Comment by spocke** [comment]
I'm closing this one since it's fixed in 4.7.0.
