### ISSUE TITLE
Drag-n-Drop image fails with TypeError: URL.createObjectURL is not a function

### ISSUE THREAD

**Issue by dstaviss** [tinymce/tinymce#6933]
Drag-n-Drop image fails with TypeError: URL.createObjectURL is not a function, 

images_upload_handler is implemented and worked in versions prior to 5.8.0

browser: chrome 91.0.4472.101
TinyMCE version: 5.8.1

tinymce.min.js:9 Uncaught (in promise) TypeError: URL.createObjectURL is not a function
    at i (tinymce.min.js:9)
    at Object.create (tinymce.min.js:9)
    at pe (plugin.min.js:9)
    at plugin.min.js:9
    at x (plugin.min.js:9)
    at plugin.min.js:9

apparently: blobUri:E(e.blobUri||URL.createObjectURL(r))  code is not a checking if function URL.createObjectURL() is implemented...

**Comment by dstaviss** [comment]
Additional observation: if Tiny loads content with <img src="data:image/png;base64,...."> (the image pasted before) the similar error is thrown:
Uncaught TypeError: URL.createObjectURL is not a function
    at i (tinymce.min.js:9)
    at Object.create (tinymce.min.js:9)
    at tinymce.min.js:9
    at Object.map (tinymce.min.js:9)
    at tinymce.min.js:9
    at Object.h (tinymce.min.js:9)
    at tinymce.min.js:9
    at Object.r (tinymce.min.js:9)
    at t (tinymce.min.js:9)
    at Y (tinymce.min.js:9)
    at Array.<anonymous> (tinymce.min.js:9)
    at Object.parse (tinymce.min.js:9)
    at tinymce.min.js:9
    at Object.fold (tinymce.min.js:9)
    at Qp (tinymce.min.js:9)
    at Object.setContent (tinymce.min.js:9)

TinyMCE version: 5.8.1

Does Tiny has global variable named URL? This clashes with the modern browsers and need to be changed to something more appropriate/unique
Thx
