### ISSUE TITLE
TypeError thrown with inline editor when using fixed_toolbar_container (4.2.0)

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2285]
Description of problem: after upgrading to 4.2.0 (from 4.1.10), a TypeError is thrown when the toolbar is hidden for an inline editor when using fixed_toolbar_container.

Steps to reproduce:

1. initialize editor with, for example,

inline: true,
fixed_toolbar_container: '#toolbar',

2. click on content to edit
3. click away for editor to lose focus and hide toolbar
4. click on content to edit

Expected result: toolbar should appear on step (2), hide on step (3), show on step (4).

Actual result: toolbar appears on step (2), hides on step (3), TypeError is thrown in console, toolbar will not show again

Uncaught TypeError: panel.hideAll is not a function
hide	@	theme.js:629

If I comment-out theme.js:629, it works fine; looks like the panel object doesn't have the same prototype as a floatpanel, as found here in theme.js:

type: inlineToolbarContainer ? 'panel' : 'floatpanel',

Thanks.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7573](http://archive.tinymce.com/develop/bugtracker_view.php?id=7573) posted by [TrevorPT](http://archive.tinymce.com/profile.php?name=TrevorPT)_

> _**Tags:** [chrome chrome]_
> _**Status:** Closed_
> _**Resolution:** Fixed_
> _**Attached URL:** http://fiddle.tinymce.com/pQeaab_
