### ISSUE TITLE
Backward compatibility of minor versions of TinyMCE 4.

### ISSUE THREAD

**Issue by lk-geimfari** [tinymce/tinymce#3791]
I have created plugin which insert google map to TinyMCE 4, but i have problem with old minor version.

It's perfectly worked with TinyMCE **4.6.4**, but with **4.4.3** (unfortunately, 4.4.3 is version which used in the project I'm working on.) i have this:

```
Uncaught TypeError: (r[n] || n).replace is not a function
    at Object.translate (tinymce.min.js:11)
    at Object.translate (tinymce.min.js:12)
    at Function.e.translate (tinymce.min.js:13)
    at translate (tinymce.min.js:8)
    at t.encode (tinymce.min.js:8)
    at t.renderHtml (tinymce.min.js:13)
    at t.renderHtml (tinymce.min.js:8)
    at t.<anonymous> (tinymce.min.js:12)
    at Object.n [as each] (tinymce.min.js:3)
    at t.each (tinymce.min.js:8)
```

Where is a problem? I can't understand.

**Comment by fyrkant** [comment]
It is impossible to know what is wrong with only that stack trace I am afraid, are you able to reproduce the problem in a fiddle? When does the problem occur, when you load your plugin?

**Comment by lk-geimfari** [comment]
@fyrkant Of course. https://codepen.io/likid_geimfari/pen/pwOeRX -> Insert -> Map. It's does not work with TinyMCE 4.4.3, but work with 4.6.4

**Comment by fyrkant** [comment]
Ah ok, sorry I misunderstood the problem, if it is working with the latest version of TinyMCE I would just recommend updating to that.
